### ISSUE TITLE
Library function for access to buttons

### ISSUE THREAD

**Issue by njh** [Industruino/UC1701#2]
Hello,

The "IndustruinoDemoCode" example shows how to access the buttons and I have semi-successfully copy-pasted the code. But it would be better if it was available as a library function - that would make it easier to use and more easily benefit to improvements to the library.

But that bring question - is the library just for the screen, or for the whole Industruino top board.

nick.

**Comment by Industruino** [comment]
Hi Nick,

Sorry for my late reply, I'm a bit overwhelmed with production work at the moment...
I agree, a library for the button functions would be useful. But you are lucky, we had another customer recently who actually made a simple library for this!
This is the link to his library:
https://github.com/summitsystemsinc/IndIOButtonPanel

I will soon include it on our documentation page and github.

Please let me know if I can help with anything, I'm really excited to have interactive customers like you :)

Best Regards,

Loic

**Comment by njh** [comment]
I have given it a go and it works well!

Thanks for pointing it out to me.
